import os
import sys
import json
import time
import shutil
import torch
import soundfile as sf
import numpy as np

# Ensure UTF-8 stdout
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

BASE_DIR = r"c:\Users\Quang Huy Nugyen\divergency-reviewer-site"
SITE_AUDIO_DIR = os.path.join(BASE_DIR, "content", "gameplay", "audio")
UNITY_SOUND_DIR = r"C:\Users\Quang Huy Nugyen\LF2Revie\Assets\Sound\DevLogs"
STUDIO_GEN_DIR = r"C:\Users\Quang Huy Nugyen\Videos\Marketting_game\Music_SoundFX_MrLinken91\Music_SoundFX_MrLinken91\output\generated"
ITEMS_FILE = os.path.join(BASE_DIR, "scripts", "all_parsed_audio_items.json")
STATUS_FILE = os.path.join(BASE_DIR, "scripts", "batch_status.json")

os.makedirs(SITE_AUDIO_DIR, exist_ok=True)
os.makedirs(UNITY_SOUND_DIR, exist_ok=True)
os.makedirs(STUDIO_GEN_DIR, exist_ok=True)

MASTER_SFX_INSTRUCTION = (
    " Isolated sound effect for a tactile pixel-art arcade action game set in a damp industrial sewer. "
    "Punchy, compact and readable in a crowded fight, with believable material texture and restrained arcade emphasis. "
    "One event only, immediate clean onset, complete short natural decay. "
    "No music, speech, ambient bed, added footsteps, extra attacks, distortion, clipping, or long baked-in room reverb."
)

SFX_NEGATIVE_PROMPT = (
    "music, musical instruments, melody, chords, choir, singing, speech, vocal noise, "
    "harsh distortion, clipping, digital clipping, white noise, static, hiss, hum, background rumble, wall of sound"
)

MUSIC_NEGATIVE_PROMPT = (
    "vocals, singing, speech, spoken words, screaming, dialogue, "
    "game sound effects, gunshots, explosions, trailer booms, distortion, clipping, static"
)

def trim_silence(arr, sr, threshold=0.015, pre_pad_ms=8, post_pad_ms=180):
    # arr is 2D: (samples, channels)
    env = np.max(np.abs(arr), axis=1)
    active = np.where(env > threshold)[0]
    if len(active) == 0:
        return arr
    start_idx = max(0, active[0] - int(sr * pre_pad_ms / 1000))
    end_idx = min(len(arr), active[-1] + int(sr * post_pad_ms / 1000))
    trimmed = arr[start_idx:end_idx]
    # Small fade out at the very end to avoid pop
    fade_len = min(int(sr * 0.02), len(trimmed) // 4)
    if fade_len > 0:
        fade = np.linspace(1.0, 0.0, fade_len)[:, np.newaxis]
        trimmed[-fade_len:] *= fade
    return trimmed

def sync_file(file_path, category, prompt, duration):
    filename = os.path.basename(file_path)
    site_path = os.path.join(SITE_AUDIO_DIR, filename)
    if os.path.abspath(file_path) != os.path.abspath(site_path):
        shutil.copy2(file_path, site_path)
        
    cat_dir = os.path.join(UNITY_SOUND_DIR, category)
    os.makedirs(cat_dir, exist_ok=True)
    unity_path = os.path.join(cat_dir, filename)
    shutil.copy2(file_path, unity_path)
    
    studio_path = os.path.join(STUDIO_GEN_DIR, filename)
    shutil.copy2(file_path, studio_path)
    
    meta_path = os.path.splitext(studio_path)[0] + ".json"
    meta = {
        "id": os.path.splitext(filename)[0],
        "category": category,
        "engine": "stable_audio_3",
        "prompt": prompt,
        "duration": duration,
        "file": filename,
        "created_at": time.time()
    }
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)

def main():
    print("=======================================================")
    print("Starting Clean High-Fidelity Audio Generation")
    print("Engine: Stable Audio 3 (Official CFG=1.0 / PCM_16)")
    print("=======================================================")
    
    from stable_audio_3 import StableAudioModel

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[+] Hardware accelerator: {device}")
    
    with open(ITEMS_FILE, "r", encoding="utf-8") as f:
        items = json.load(f)
        
    status = {}
    if os.path.exists(STATUS_FILE):
        try:
            with open(STATUS_FILE, "r", encoding="utf-8") as f:
                status = json.load(f)
        except Exception:
            status = {}

    # Separate items
    # 1. 3 Large 64s Music Loops generated by ACE-Step (MUS01, MUS02, MUS03) - keep intact!
    # 2. Short Music Stingers (MUS04, MUS05, MUS06, MUS07) -> small-music
    # 3. Ambience -> small-sfx or small-music
    # 4. SFX (Movement, Melee, Ranged, Skills, Boss, Rebound, UI, Voice) -> small-sfx
    
    sfx_items = [it for it in items if it.get("category") not in ("Music", "Ambience")]
    ambience_items = [it for it in items if it.get("category") == "Ambience"]
    stinger_items = [it for it in items if it.get("category") == "Music" and it.get("stem") not in ("mus_devlogs_practice_loop", "mus_devlogs_combat_loop", "mus_devlogs_bigmm_loop")]

    print(f"[+] Total SFX items to generate: {len(sfx_items)}")
    print(f"[+] Total Ambience items: {len(ambience_items)}")
    print(f"[+] Total Music stingers: {len(stinger_items)}")

    # Step 1: Load small-sfx
    print("\n-------------------------------------------------------")
    print("[*] Loading Stable Audio 3 [small-sfx]...")
    model_sfx = StableAudioModel.from_pretrained("small-sfx", device=device, model_half=(device == "cuda"))
    sr_sfx = int(model_sfx.model_config.get("sample_rate", 44100))
    print("[+] small-sfx loaded successfully!")

    # Generate all SFX
    total_sfx = len(sfx_items)
    for idx, item in enumerate(sfx_items, 1):
        stem = item["stem"]
        filename = item["file_name"]
        cat = item["category"]
        raw_prompt = item["prompt"]
        
        # Decide generation duration and target
        # For explosion or heavy impacts, use 3.5s; for quick oneshots, 2.5s
        if "explode" in stem or "grenade_explode" in stem or "burst" in stem:
            gen_dur = 3.8
        elif "loop" in stem:
            gen_dur = 3.5
        elif "bigmm" in stem:
            gen_dur = 2.8
        else:
            gen_dur = 2.5
            
        full_prompt = raw_prompt.strip()
        if not full_prompt.endswith("."):
            full_prompt += "."
        full_prompt += MASTER_SFX_INSTRUCTION

        dest_file = os.path.join(SITE_AUDIO_DIR, filename)

        print(f"\n[{idx}/{total_sfx}] SFX: {filename} [{cat}]")
        print(f"    Prompt: {raw_prompt[:85]}...")
        
        t0 = time.time()
        try:
            audio = model_sfx.generate(
                prompt=full_prompt,
                negative_prompt=SFX_NEGATIVE_PROMPT,
                duration=gen_dur,
                steps=8,
                cfg_scale=1.0,  # Official Stable Audio 3 CFG scale
                seed=1000 + idx,
                batch_size=1,
                truncate_output_to_duration=True,
                chunked_decode=True
            )
            audio = audio.to(torch.float32).cpu()
            peak = audio.abs().max().item()
            if peak > 1e-8:
                audio = audio / peak * 0.95
            
            arr = audio[0].transpose(0, 1).numpy() # (samples, channels)
            
            # If not a seamless loop, trim lead-in and trailing silence
            if "loop" not in stem:
                final_arr = trim_silence(arr, sr_sfx)
            else:
                final_arr = arr
                
            sf.write(dest_file, final_arr, sr_sfx, subtype='PCM_16')
            sync_file(dest_file, cat, raw_prompt, len(final_arr)/sr_sfx)
            
            elapsed = time.time() - t0
            rms = np.sqrt(np.mean(final_arr**2))
            actual_dur = len(final_arr) / sr_sfx
            print(f"    [V] Done in {elapsed:.1f}s | Dur: {actual_dur:.2f}s | Peak: {np.max(np.abs(final_arr)):.2f} | RMS: {rms:.4f}")
            
            status[stem] = {
                "status": "success",
                "file": filename,
                "category": cat,
                "size_kb": int(os.path.getsize(dest_file) / 1024),
                "duration": round(actual_dur, 2),
                "rms": round(float(rms), 4)
            }
        except Exception as e:
            print(f"    [!] Error generating {filename}: {e}")
            status[stem] = {
                "status": "failed",
                "file": filename,
                "category": cat,
                "error": str(e)
            }

        # Save status periodically
        if idx % 10 == 0:
            with open(STATUS_FILE, "w", encoding="utf-8") as f:
                json.dump(status, f, indent=2, ensure_ascii=False)

    # Free small-sfx from memory
    del model_sfx
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # Step 2: Load small-music for Ambience and Stingers
    print("\n-------------------------------------------------------")
    print("[*] Loading Stable Audio 3 [small-music]...")
    model_mus = StableAudioModel.from_pretrained("small-music", device=device, model_half=(device == "cuda"))
    sr_mus = int(model_mus.model_config.get("sample_rate", 44100))
    print("[+] small-music loaded successfully!")

    # Music stingers
    for idx, item in enumerate(stinger_items, 1):
        stem = item["stem"]
        filename = item["file_name"]
        raw_prompt = item["prompt"]
        cat = "Music"
        
        if stem == "mus_devlogs_boss_release":
            dur = 2.5
        elif stem == "mus_devlogs_victory":
            dur = 5.0
        elif stem == "mus_devlogs_defeat":
            dur = 4.0
        elif stem == "mus_devlogs_start":
            dur = 2.0
        else:
            dur = 3.0

        dest_file = os.path.join(SITE_AUDIO_DIR, filename)
        print(f"\n[Stinger {idx}/{len(stinger_items)}] {filename} (dur={dur}s)")
        print(f"    Prompt: {raw_prompt[:85]}...")
        t0 = time.time()
        try:
            audio = model_mus.generate(
                prompt=raw_prompt,
                negative_prompt=MUSIC_NEGATIVE_PROMPT,
                duration=dur,
                steps=8,
                cfg_scale=1.0,
                seed=2000 + idx,
                batch_size=1,
                truncate_output_to_duration=True,
                chunked_decode=True
            )
            audio = audio.to(torch.float32).cpu()
            peak = audio.abs().max().item()
            if peak > 1e-8:
                audio = audio / peak * 0.95
            arr = audio[0].transpose(0, 1).numpy()
            
            sf.write(dest_file, arr, sr_mus, subtype='PCM_16')
            sync_file(dest_file, cat, raw_prompt, dur)
            elapsed = time.time() - t0
            rms = np.sqrt(np.mean(arr**2))
            print(f"    [V] Done in {elapsed:.1f}s | RMS: {rms:.4f}")
            status[stem] = {
                "status": "success",
                "file": filename,
                "category": cat,
                "size_kb": int(os.path.getsize(dest_file) / 1024),
                "duration": dur,
                "rms": round(float(rms), 4)
            }
        except Exception as e:
            print(f"    [!] Error generating stinger {filename}: {e}")

    # Ambience loops
    for idx, item in enumerate(ambience_items, 1):
        stem = item["stem"]
        filename = item["file_name"]
        raw_prompt = item["prompt"]
        cat = "Ambience"
        dur = 15.0 if "loop" in stem else 2.5
        dest_file = os.path.join(SITE_AUDIO_DIR, filename)
        print(f"\n[Ambience {idx}/{len(ambience_items)}] {filename} (dur={dur}s)")
        t0 = time.time()
        try:
            audio = model_mus.generate(
                prompt=raw_prompt,
                negative_prompt="music, drums, synth, vocals, speech, distortion",
                duration=dur,
                steps=8,
                cfg_scale=1.0,
                seed=3000 + idx,
                batch_size=1,
                truncate_output_to_duration=True,
                chunked_decode=True
            )
            audio = audio.to(torch.float32).cpu()
            peak = audio.abs().max().item()
            if peak > 1e-8:
                audio = audio / peak * 0.95
            arr = audio[0].transpose(0, 1).numpy()
            sf.write(dest_file, arr, sr_mus, subtype='PCM_16')
            sync_file(dest_file, cat, raw_prompt, dur)
            elapsed = time.time() - t0
            rms = np.sqrt(np.mean(arr**2))
            print(f"    [V] Done in {elapsed:.1f}s | RMS: {rms:.4f}")
            status[stem] = {
                "status": "success",
                "file": filename,
                "category": cat,
                "size_kb": int(os.path.getsize(dest_file) / 1024),
                "duration": dur,
                "rms": round(float(rms), 4)
            }
        except Exception as e:
            print(f"    [!] Error generating ambience {filename}: {e}")

    del model_mus
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # Final status save
    with open(STATUS_FILE, "w", encoding="utf-8") as f:
        json.dump(status, f, indent=2, ensure_ascii=False)
        
    print("\n=======================================================")
    print("[SUCCESS] All SFX, Stingers, and Ambience generated with high fidelity!")
    print("=======================================================")

if __name__ == "__main__":
    main()
